### ISSUE TITLE
IOException and NullPointerException from urbandictionary command 503 response from UD

### ISSUE THREAD

**Issue by BullShark** [BullShark/JRobo#3]
[---]   :StingRay!stingray@protectedhost-B7B589D8.static.rackspacecloud.com PRIVMSG #blackhats :^ud adeel

java.io.IOException: Server returned HTTP response code: 503 for URL: http://api.urbandictionary.com/v0/define?term=adeel
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
        at jrobo.UrbanDict.getJson(UrbanDict.java:86)
        at jrobo.UrbanDict.getFormattedUrbanDef(UrbanDict.java:107)
        at jrobo.BotCommand.urbanDictionaryHelper(BotCommand.java:350)
        at jrobo.BotCommand.bCommander(BotCommand.java:105)
        at jrobo.JRobo.initiate(JRobo.java:127)
        at jrobo.JRobo.main(JRobo.java:212)
Exception in thread "main" java.lang.NullPointerException
        at jrobo.UrbanDict.getFormattedUrbanDef(UrbanDict.java:114)
        at jrobo.BotCommand.urbanDictionaryHelper(BotCommand.java:350)
        at jrobo.BotCommand.bCommander(BotCommand.java:105)
        at jrobo.JRobo.initiate(JRobo.java:127)
        at jrobo.JRobo.main(JRobo.java:212)

**Comment by BullShark** [comment]
I could not reproduce this. The bot command

.ud adeel

Returned the expected definitions from Urban Dictionary.
