### ISSUE TITLE
Unhandled exception with json/gson in Pirate Bay search

### ISSUE THREAD

**Issue by BullShark** [BullShark/JRobo#6]
[java] [---]       :bullshark[m]!bullsharkm@2001:470:1af1:104:0:0:0:350b PRIVMSG #blackhats :.pirate -s activate windows 8
     [java] http://odin.root.sx/thepiratebay.php?name=%20activate%20windows%208&orderby=s&limit=5
     [java] Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 5
     [java]     at com.google.gson.Gson.fromJson(Gson.java:806)
     [java]     at com.google.gson.Gson.fromJson(Gson.java:761)
     [java]     at com.google.gson.Gson.fromJson(Gson.java:710)
     [java]     at com.google.gson.Gson.fromJson(Gson.java:682)
     [java]     at jrobo.PirateBay.getFormattedResult(PirateBay.java:131)
     [java]     at jrobo.BotCommand.pirateHelper(BotCommand.java:692)
     [java]     at jrobo.BotCommand.bCommander(BotCommand.java:155)
     [java]     at jrobo.JRobo.initiate(JRobo.java:121)
     [java]     at jrobo.JRobo.main(JRobo.java:185)
     [java] Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 5
     [java]     at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
     [java]     at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:306)
     [java]     at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
     [java]     at com.google.gson.Gson.fromJson(Gson.java:795)
     [java]     ... 8 more
     [java] Java Result: 1

**Comment by BullShark** [comment]
Added exception handling for JsonSyntaxException, and thepiratebay.php is lost in oblivion.
